import re

def classify_resume_origin(text):
    """
    Classify the resume as AI-Generated or Human-Written using heuristic keyword patterns.
    """

    ai_indicators = [
        "ChatGPT", "GPT-3", "GPT-4", "OpenAI", "language model", 
        "generated by", "AI generated", "This resume was created using",
        "automatically generated", "as an AI language model",
        "I am an AI model", "generated with", "Created using ChatGPT"
    ]

    # Count how many AI indicators appear in text
    match_count = sum(1 for kw in ai_indicators if kw.lower() in text.lower())

    # Additional heuristic checks (patterns typical to AI-generated content)
    generic_phrases = [
        r"\bAs an AI language model\b",
        r"\bI do not have personal experiences\b",
        r"\bI am unable to perform actions\b"
    ]
    for pattern in generic_phrases:
        if re.search(pattern, text, re.IGNORECASE):
            match_count += 2  # Increase score for strong AI hints

    # Threshold-based classification
    if match_count >= 1:
        return "AI-Generated"
    else:
        return "Human-Written"
